### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nugend** [tuor713/trino-kdb#8]
Hi, might have cause to use this project. Seems like no license is indicated. Safe to assume a permissive license or did you have something else in mind?

PS: Couldn’t seem to find a way to reach out through email or anything, but would appreciate picking your brain about how well you feel kdb and trino work together sometime

**Comment by tuor713** [comment]
Good question - yeah I had in general intended it to be permissive. Will check over the weekend and add an explicit LICENSE file.

**Comment by zeddit** [comment]
javakdb have reached 2.0 to support jvm 17+, and it is incompatible with javakdb 1.0 because it changed some data types for datetime. I have migirated trino-kdb to support javakdb 2.0. 
However, I have two problems. 
one is my query through trino-kdb suffer from a large startup delay, which means even I pull a small dataset, it still needs about 10+ seconds to finished. Do you know what causes such delays and give me some advices about it.
another one is I found trino update their scaffold of data plugin which means your awesome trino-kdb only support trino less than version 385(up to now, trino reached version 421). I wonder would you want to upgrade your project. thanks.

**Comment by tuor713** [comment]
Interesting will explore javakdb 2.0 as well :) As for 385 agreed I have not upgrade version for a while - usually not too much, so I might do this in not too long.

As for the startup delay few things I can think of but really would need more debug from the logs.

- You have got dynamic stats enabled and the query needs stats, which get created at query time (and take long).
- There are other processes running against the KDB and block execution (since KDB is single threaded in most common usage)

**Comment by zeddit** [comment]
thanks for your reply.
